### ISSUE TITLE
被检测代码不显示下划波浪线

### ISSUE THREAD

**Issue by hfg5961107** [ouyangpeng/XTCLint#3]
请问我目前没有使用上传到本地maven仓库的插件方式，使用的直接aar添加依赖的方式。为什么没有下划波浪线等提示呢。但是直接执行gradlew lint能够输入xml等详细文件。不知道问题在哪儿？

**Comment by hfg5961107** [comment]
我尝试了lint 3.x，因为我的as是3.x版本。但是还是没效果。我感觉没有自动加载项目中的自定义lint.xml文件。

**Comment by ouyangpeng** [comment]
这一份代码是 gradle 2.x的代码   使用as 3.x版本 可能加载不成功吧。
请自行将代码全部用kotlin以及gradle 3.x的语法进行重写
